{{- if .Values.postgresql.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "sidar.fullname" . }}-postgresql
spec:
  serviceName: {{ include "sidar.fullname" . }}-postgresql
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: postgresql
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: postgresql
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: postgresql
          image: {{ .Values.postgresql.image }}
          ports:
            - name: postgresql
              containerPort: {{ .Values.postgresql.port }}
          envFrom:
            - secretRef:
                name: {{ include "sidar.fullname" . }}-postgresql
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgresql-data
      spec:
        accessModes: ["ReadWriteOnce"]
        {{- if .Values.postgresql.storage.storageClassName }}
        storageClassName: {{ .Values.postgresql.storage.storageClassName | quote }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.postgresql.storage.size }}
{{- end }}