"""Autonomous self-healing orchestrator loop for Sidar."""

from __future__ import annotations

import argparse
import json
import subprocess  # nosec B404
import time
from pathlib import Path
import xml.etree.ElementTree as ET


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Run autonomous test-heal-upload loop")
    parser.add_argument("--test-cmd", default="bash run_tests.sh", help="Command used to run tests")
    parser.add_argument(
        "--coverage-json",
        default="coverage.json",
        help="Coverage JSON file path generated by tests",
    )
    parser.add_argument(
        "--junit-xml",
        default="artifacts/test_reports/pytest-junit.xml",
        help="JUnit XML test result path generated by tests",
    )
    parser.add_argument(
        "--auto-heal-cmd",
        default="python scripts/auto_heal.py --log tests/pytest.log --source pytest",
        help="Command that triggers AI remediation",
    )
    parser.add_argument(
        "--github-upload-cmd",
        default="python github_upload.py",
        help="Command used for GitHub upload",
    )
    parser.add_argument("--interval-seconds", type=int, default=5, help="Pause between loop iterations")
    parser.add_argument(
        "--max-iterations", type=int, default=0, help="Safety limit; 0 means run forever"
    )
    return parser.parse_args()


def run_command(command: str) -> int:
    print(f"➡️ Çalıştırılıyor: {command}")
    completed = subprocess.run(command, shell=True, check=False)  # nosec B602
    return int(completed.returncode)


def read_coverage_percent(coverage_json: Path) -> float | None:
    if not coverage_json.exists():
        return None
    payload = json.loads(coverage_json.read_text(encoding="utf-8"))
    totals = payload.get("totals", {})
    percent = totals.get("percent_covered")
    if percent is None:
        percent = totals.get("percent_covered_display")
    try:
        return float(percent)
    except (TypeError, ValueError):
        return None


def read_junit_failures(junit_xml: Path) -> tuple[int, int] | None:
    if not junit_xml.exists():
        return None
    root = ET.fromstring(junit_xml.read_text(encoding="utf-8"))
    if root.tag == "testsuite":
        failures = int(root.attrib.get("failures", 0)) + int(root.attrib.get("errors", 0))
        tests = int(root.attrib.get("tests", 0))
        return tests, failures

    tests = 0
    failures = 0
    for suite in root.findall("testsuite"):
        tests += int(suite.attrib.get("tests", 0))
        failures += int(suite.attrib.get("failures", 0)) + int(suite.attrib.get("errors", 0))
    return tests, failures


def should_heal(coverage_pct: float | None, junit_stats: tuple[int, int] | None, test_exit: int) -> bool:
    if test_exit != 0:
        return True
    if coverage_pct is None or coverage_pct < 100.0:
        return True
    if junit_stats is None:
        return True
    _, failures = junit_stats
    return failures > 0


def main() -> int:
    args = parse_args()
    coverage_json = Path(args.coverage_json)
    junit_xml = Path(args.junit_xml)

    iteration = 0
    while True:
        iteration += 1
        print(f"\n🔁 Otonom döngü iterasyonu #{iteration}")

        test_exit = run_command(args.test_cmd)
        coverage_pct = read_coverage_percent(coverage_json)
        junit_stats = read_junit_failures(junit_xml)

        if should_heal(coverage_pct, junit_stats, test_exit):
            print(
                "⚠️ Kalite kapıları karşılanmadı "
                f"(exit={test_exit}, coverage={coverage_pct}, junit={junit_stats})."
            )
            heal_exit = run_command(args.auto_heal_cmd)
            if heal_exit != 0:
                print("❌ AI self-heal komutu başarısız oldu; yine de upload denenecek.")
        else:
            print(f"✅ Testler başarılı ve coverage %100: {coverage_pct}")

        upload_exit = run_command(args.github_upload_cmd)
        if upload_exit != 0:
            print("❌ GitHub upload komutu başarısız oldu.")

        if args.max_iterations > 0 and iteration >= args.max_iterations:
            print("🛑 max-iterations limitine ulaşıldı, döngü sonlandırılıyor.")
            break

        time.sleep(max(0, args.interval_seconds))

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
