{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "sidar.fullname" . }}-postgresql
spec:
  ports:
    - port: {{ .Values.postgresql.port }}
      targetPort: postgresql
      name: postgresql
  selector:
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
