"""File IO security helpers for CodeManager."""

from __future__ import annotations

import fnmatch
import logging
from pathlib import Path
from typing import Any, cast

from managers.code.patcher import apply_exact_block_patch

logger = logging.getLogger(__name__)


def strip_markdown_code_fences(content: str) -> str:
    """Strip surrounding markdown code fences from generated content."""
    text = str(content or "").strip()
    if text.startswith("```"):
        lines = text.splitlines()
        if lines and lines[0].startswith("```"):  # pragma: no cover
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        text = "\n".join(lines).strip()
    return text


def read_file(manager: Any, path: str, line_numbers: bool = True) -> tuple[bool, str]:
    """Read a file after CodeManager security checks."""
    if not manager.security_adapter.can_read(path):
        return False, "[OpenClaw] Okuma yetkisi yok veya tehlikeli yol reddedildi."
    try:
        target = Path(path).resolve()
        if not target.exists():
            return False, f"Dosya bulunamadı: {path}"
        if target.is_dir():
            return False, f"Belirtilen yol bir dizin: {path}"
        with manager._lock:
            with open(target, encoding="utf-8", errors="replace") as f:
                content = f.read()
            manager._files_read += 1
        logger.debug("Dosya okundu: %s (%d karakter)", path, len(content))
        if line_numbers:
            lines = content.splitlines()
            width = len(str(len(lines)))
            numbered = "\n".join(
                f"{str(i + 1).rjust(width)}\t{line}" for i, line in enumerate(lines)
            )
            return True, numbered
        return True, content
    except PermissionError:
        return False, f"[OpenClaw] Erişim reddedildi: {path}"
    except Exception as exc:
        return False, f"Okuma hatası: {exc}"


def write_file(manager: Any, path: str, content: str, validate: bool = True) -> tuple[bool, str]:
    """Write a file after security and optional syntax validation checks."""
    if not manager.security_adapter.can_write(path):
        return False, manager.security_adapter.safe_write_denial(path)
    if validate and path.endswith(".py"):
        ok, msg = manager.validate_python_syntax(content)
        if not ok:
            return False, f"Sözdizimi hatası, dosya kaydedilmedi:\n{msg}"
    try:
        target = Path(path)
        target.parent.mkdir(parents=True, exist_ok=True)
        with manager._lock:
            with open(target, "w", encoding="utf-8") as f:
                f.write(content)
            manager._files_written += 1
            manager._post_process_written_file(target)
        logger.info("Dosya yazıldı: %s", path)
        return True, f"Dosya başarıyla kaydedildi: {path}"
    except PermissionError:
        return False, f"[OpenClaw] Yazma erişimi reddedildi: {path}"
    except Exception as exc:
        return False, f"Yazma hatası: {exc}"


def write_generated_test(
    manager: Any,
    path: str,
    content: str,
    *,
    append: bool = True,
    marker: str = "# Generated by CoverageAgent",
) -> tuple[bool, str]:
    """Safely write deterministic pytest content generated by coverage automation."""
    del marker
    normalized = strip_markdown_code_fences(content)
    if not normalized.strip():
        return False, "Yazılacak pytest içeriği boş."
    target = Path(path)
    if append and target.exists():
        ok, current = manager.read_file(str(target), line_numbers=False)
        if not ok:
            return False, current
        if normalized in current:
            return True, f"Test içeriği zaten mevcut: {path}"
        separator = "\n\n" if current.strip() else ""
        return cast(
            tuple[bool, str],
            manager.write_file(
                str(target), f"{current.rstrip()}{separator}{normalized.rstrip()}\n", validate=True
            ),
        )
    return cast(
        tuple[bool, str],
        manager.write_file(str(target), f"{normalized.rstrip()}\n", validate=True),
    )


def patch_file(
    manager: Any, path: str, target_block: str, replacement_block: str
) -> tuple[bool, str]:
    ok, content = manager.read_file(path, line_numbers=False)
    if not ok:
        return False, content
    ok, patched_or_error = apply_exact_block_patch(content, target_block, replacement_block)
    if not ok:
        return False, patched_or_error
    return cast(tuple[bool, str], manager.write_file(path, patched_or_error, validate=True))


def glob_search(manager: Any, pattern: str, base_path: str = ".") -> tuple[bool, str]:
    """Find files by glob pattern under a safe base path."""
    try:
        base = Path(base_path).resolve()
        if not base.exists():
            return False, f"Dizin bulunamadı: {base_path}"
        if not base.is_dir():
            return False, f"Belirtilen yol bir dizin değil: {base_path}"
        if not manager.security_adapter.is_path_under(str(base), manager.base_dir):
            return False, f"[OpenClaw] Arama dizini proje kökü dışında: {base}"
        matches = [p for p in base.rglob(pattern) if p.is_file()]
        safe_matches = [m for m in matches if manager.security_adapter.can_read(str(m))]
        safe_matches.sort(key=lambda p: p.stat().st_mtime, reverse=True)
        if not safe_matches:
            return True, f"Eşleşen dosya bulunamadı: `{pattern}` ({base_path})"
        lines = [f"Glob sonuçları — `{pattern}` ({len(safe_matches)} eşleşme):"]
        for match in safe_matches[: manager.max_search_results]:
            lines.append(f"- {match}")
        return True, "\n".join(lines)
    except Exception as exc:
        return False, f"Glob arama hatası: {exc}"


def grep_files(
    manager: Any,
    pattern: str,
    path: str = ".",
    file_glob: str = "*",
    context: int = 2,
) -> tuple[bool, str]:
    """Search text in files with a safe path and glob filter."""
    try:
        target = Path(path).resolve()
        files_to_search: list[Path] = []
        if target.is_file():
            files_to_search = [target]
        elif target.is_dir():
            if "**" in file_glob or "/" in file_glob:
                files_to_search = [f for f in target.rglob(file_glob) if f.is_file()]
            else:
                files_to_search = [
                    f
                    for f in target.rglob("*")
                    if f.is_file() and fnmatch.fnmatch(f.name, file_glob)
                ]
        else:
            return False, f"Yol bulunamadı: {path}"
        results: list[str] = []
        match_count = 0
        files_with_matches = 0
        for fp in sorted(files_to_search):
            if not manager.security_adapter.can_read(str(fp)):
                continue
            try:
                lines = fp.read_text(encoding="utf-8", errors="replace").splitlines()
            except Exception:
                continue
            file_matches: list[str] = []
            for idx, line in enumerate(lines):
                if pattern in line:
                    match_count += 1
                    start = max(0, idx - context)
                    end = min(len(lines), idx + context + 1)
                    ctx_lines = [
                        f"{line_no + 1:4d}: {lines[line_no]}" for line_no in range(start, end)
                    ]
                    file_matches.append("\n".join(ctx_lines))
            if file_matches:
                files_with_matches += 1
                results.append(f"\n### {fp}\n" + "\n---\n".join(file_matches))
            if len(results) >= manager.max_search_results:
                break
        if not results:
            return True, f"Eşleşme bulunamadı: `{pattern}` ({path}, filtre: {file_glob})"
        return True, f"{files_with_matches} dosyada {match_count} eşleşme\n" + "\n".join(results)
    except Exception as exc:
        return False, f"Grep arama hatası: {exc}"


def list_directory(manager: Any, path: str = ".") -> tuple[bool, str]:
    try:
        target = Path(path).resolve()
        if not target.exists():
            return False, f"Dizin bulunamadı: {path}"
        if not target.is_dir():
            return False, f"Belirtilen yol bir dizin değil: {path}"
        if not manager.security_adapter.is_path_under(str(target), manager.base_dir):
            return False, f"[OpenClaw] Listeleme dizini proje kökü dışında: {target}"
        items = sorted(target.iterdir(), key=lambda p: (p.is_file(), p.name.lower()))
        lines = [f"📁 {path}/"]
        for item in items[: manager.max_search_results]:
            suffix = "/" if item.is_dir() else ""
            lines.append(f"- {item.name}{suffix}")
        return True, "\n".join(lines)
    except Exception as exc:
        return False, f"Dizin listeleme hatası: {exc}"


__all__ = [
    "glob_search",
    "grep_files",
    "list_directory",
    "patch_file",
    "read_file",
    "strip_markdown_code_fences",
    "write_file",
    "write_generated_test",
]
